[2025-05-07T12:55:19.952+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=retrain_after_updated permission to 509
[2025-05-07T12:55:19.955+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=retrain_after_updated permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=retrain_after_updated'
[2025-05-07T12:55:20.062+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=retrain_after_updated permission to 509
[2025-05-07T12:55:20.064+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=retrain_after_updated permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=retrain_after_updated'
[2025-05-07T12:55:20.126+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: anime_etl_pipeline.retrain_after_updated manual__2025-05-07T12:54:45.110872+00:00 [queued]>
[2025-05-07T12:55:20.161+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: anime_etl_pipeline.retrain_after_updated manual__2025-05-07T12:54:45.110872+00:00 [queued]>
[2025-05-07T12:55:20.162+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2025-05-07T12:55:20.226+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): retrain_after_updated> on 2025-05-07 12:54:45.110872+00:00
[2025-05-07T12:55:20.236+0000] {standard_task_runner.py:57} INFO - Started process 344 to run task
[2025-05-07T12:55:20.242+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'anime_etl_pipeline', 'retrain_after_updated', 'manual__2025-05-07T12:54:45.110872+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpactxv724']
[2025-05-07T12:55:20.244+0000] {standard_task_runner.py:85} INFO - Job 207: Subtask retrain_after_updated
[2025-05-07T12:55:20.390+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=retrain_after_updated permission to 509
[2025-05-07T12:55:20.391+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=retrain_after_updated permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:54:45.110872+00:00/task_id=retrain_after_updated'
[2025-05-07T12:55:20.393+0000] {task_command.py:415} INFO - Running <TaskInstance: anime_etl_pipeline.retrain_after_updated manual__2025-05-07T12:54:45.110872+00:00 [running]> on host b21373046c31
[2025-05-07T12:55:21.221+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='anime_etl_pipeline' AIRFLOW_CTX_TASK_ID='retrain_after_updated' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T12:54:45.110872+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T12:54:45.110872+00:00'
[2025-05-07T12:55:22.104+0000] {logging_mixin.py:151} INFO - üöÄ Retrain process started...
[2025-05-07T12:55:22.198+0000] {logging_mixin.py:151} INFO - Old CSV file loaded successfully! (3007, 3)
[2025-05-07T12:55:22.209+0000] {logging_mixin.py:151} INFO - New CSV file loaded successfully! (1, 2)
[2025-05-07T12:55:22.483+0000] {logging_mixin.py:151} INFO - Data has been merged successfully!
[2025-05-07T12:55:27.965+0000] {retrain_run.py:23} INFO - **Step 3: Making a TFIDF Vectorizer for the corpus of the Words we have for the Recommendation System...
[2025-05-07T12:55:27.968+0000] {retrain_run.py:26} INFO - Reintializing the Preprocessed Data for the work
[2025-05-07T12:55:28.074+0000] {retrain_run.py:29} INFO - ....Making the Text into the Vectors for making the closest Recommendation...
[2025-05-07T12:55:29.909+0000] {retrain_run.py:32} INFO - **Step 4: Now making the Cosine Similarity method to find the Recommended ones...
[2025-05-07T12:55:34.389+0000] {retrain_run.py:35} INFO - .....Saving Every artifact file in the directory for the as Joblib file for futher use....
[2025-05-07T12:55:35.981+0000] {retrain_run.py:39} INFO - **Step 6: Logging All Artifacts no model making is Involved in this, Input Example to MLflow**
[2025-05-07T12:55:36.156+0000] {logging_mixin.py:151} WARNING - 2025/05/07 12:55:36 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-07T12:55:42.080+0000] {logging_mixin.py:151} INFO - üèÉ View run bustling-seal-859 at: http://mlflow:5000/#/experiments/312362872963704986/runs/d0a7e228c169449ea0712fe897822880
[2025-05-07T12:55:42.080+0000] {logging_mixin.py:151} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/312362872963704986
[2025-05-07T12:55:42.113+0000] {retrain_run.py:46} INFO - **All Artifacts File Has been Saved Successfully in MLFLOW artifacts**
[2025-05-07T12:55:42.208+0000] {logging_mixin.py:151} INFO - ‚úÖ Retrain process completed successfully.
[2025-05-07T12:55:42.209+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-07T12:55:42.231+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=anime_etl_pipeline, task_id=retrain_after_updated, execution_date=20250507T125445, start_date=20250507T125520, end_date=20250507T125542
[2025-05-07T12:55:42.339+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-07T12:55:42.374+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
