[2025-05-07T12:51:33.541+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:50:20.567594+00:00/task_id=retrain_after_updated permission to 509
[2025-05-07T12:51:33.543+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:50:20.567594+00:00/task_id=retrain_after_updated permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:50:20.567594+00:00/task_id=retrain_after_updated'
[2025-05-07T12:51:33.610+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:50:20.567594+00:00/task_id=retrain_after_updated permission to 509
[2025-05-07T12:51:33.612+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:50:20.567594+00:00/task_id=retrain_after_updated permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:50:20.567594+00:00/task_id=retrain_after_updated'
[2025-05-07T12:51:33.771+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: anime_etl_pipeline.retrain_after_updated manual__2025-05-07T12:50:20.567594+00:00 [queued]>
[2025-05-07T12:51:33.794+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: anime_etl_pipeline.retrain_after_updated manual__2025-05-07T12:50:20.567594+00:00 [queued]>
[2025-05-07T12:51:33.795+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2025-05-07T12:51:33.841+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): retrain_after_updated> on 2025-05-07 12:50:20.567594+00:00
[2025-05-07T12:51:33.847+0000] {standard_task_runner.py:57} INFO - Started process 247 to run task
[2025-05-07T12:51:33.852+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'anime_etl_pipeline', 'retrain_after_updated', 'manual__2025-05-07T12:50:20.567594+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp3j1bcth_']
[2025-05-07T12:51:33.854+0000] {standard_task_runner.py:85} INFO - Job 203: Subtask retrain_after_updated
[2025-05-07T12:51:33.991+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:50:20.567594+00:00/task_id=retrain_after_updated permission to 509
[2025-05-07T12:51:33.992+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:50:20.567594+00:00/task_id=retrain_after_updated permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/"dag_id=anime_etl_pipeline/run_id=manual__2025-05-07T12:50:20.567594+00:00/task_id=retrain_after_updated'
[2025-05-07T12:51:33.995+0000] {task_command.py:415} INFO - Running <TaskInstance: anime_etl_pipeline.retrain_after_updated manual__2025-05-07T12:50:20.567594+00:00 [running]> on host b21373046c31
[2025-05-07T12:51:34.788+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='anime_etl_pipeline' AIRFLOW_CTX_TASK_ID='retrain_after_updated' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T12:50:20.567594+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T12:50:20.567594+00:00'
[2025-05-07T12:51:35.547+0000] {logging_mixin.py:151} INFO - üöÄ Retrain process started...
[2025-05-07T12:51:35.643+0000] {logging_mixin.py:151} INFO - Old CSV file loaded successfully! (3005, 3)
[2025-05-07T12:51:35.656+0000] {logging_mixin.py:151} INFO - New CSV file loaded successfully! (2, 2)
[2025-05-07T12:51:35.901+0000] {logging_mixin.py:151} INFO - Data has been merged successfully!
[2025-05-07T12:51:40.394+0000] {retrain_run.py:23} INFO - **Step 3: Making a TFIDF Vectorizer for the corpus of the Words we have for the Recommendation System...
[2025-05-07T12:51:40.397+0000] {retrain_run.py:26} INFO - Reintializing the Preprocessed Data for the work
[2025-05-07T12:51:40.487+0000] {retrain_run.py:29} INFO - ....Making the Text into the Vectors for making the closest Recommendation...
[2025-05-07T12:51:41.573+0000] {retrain_run.py:32} INFO - **Step 4: Now making the Cosine Similarity method to find the Recommended ones...
[2025-05-07T12:51:44.661+0000] {retrain_run.py:35} INFO - .....Saving Every artifact file in the directory for the as Joblib file for futher use....
[2025-05-07T12:51:46.008+0000] {retrain_run.py:39} INFO - **Step 6: Logging All Artifacts no model making is Involved in this, Input Example to MLflow**
[2025-05-07T12:51:46.102+0000] {logging_mixin.py:151} WARNING - 2025/05/07 12:51:46 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-07T12:51:51.756+0000] {logging_mixin.py:151} INFO - üèÉ View run unique-sponge-308 at: http://mlflow:5000/#/experiments/312362872963704986/runs/c1fc0070ffbb48b08d6d84bc7980570d
[2025-05-07T12:51:51.757+0000] {logging_mixin.py:151} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/312362872963704986
[2025-05-07T12:51:51.789+0000] {retrain_run.py:46} INFO - **All Artifacts File Has been Saved Successfully in MLFLOW artifacts**
[2025-05-07T12:51:51.886+0000] {logging_mixin.py:151} INFO - ‚úÖ Retrain process completed successfully.
[2025-05-07T12:51:51.887+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-07T12:51:51.914+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=anime_etl_pipeline, task_id=retrain_after_updated, execution_date=20250507T125020, start_date=20250507T125133, end_date=20250507T125151
[2025-05-07T12:51:52.041+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-07T12:51:52.076+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
